# Generated by Django 5.0.6 on 2024-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
