# Generated by Django 5.0.6 on 2024-06-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookborrowmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookreturnmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
