# Generated by Django 5.0.6 on 2024-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_price',
            field=models.IntegerField(default=0),
        ),
    ]
