# Generated by Django 5.0.6 on 2024-06-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookmodel_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_quantity',
        ),
    ]
