# Generated by Django 5.0.6 on 2024-06-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookmodel_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='book_quantity',
            field=models.IntegerField(default=5),
        ),
    ]
